const String AppTitle = "app-title",
    CreateAccount = "create-account",
    Login = "login",
    WhatYourName = "what-is-your-name",
    AddProfilePhoto = "add-profile-photo",
    WhatYourEmail = "what-your-email",
    CreateAPassword = "create-a-password",
    RegisterCompletedTitle = "register-completed",
    RegisterCompeltedMsg = "register-completed-msg",
    OK = "ok",
    YES = "yes",
    Welcome = "welcome",
    Email = "email",
    Name = "name",
    EnterYourEmail = "enter-your-email",
    EnterYourName = "enter-your-name",
    Password = "password",
    EnterYourPassword = "enter-your-password",
    Enter = "enter",
    ForgotPassword = "forgot-password",
    NewUserQuestion = "new_user_question",
    Register = "register",
    NameIsEmpty = "name-empty",
    EmailIsEmpty = "email-empty",
    EmailInvalid = "email-invalid",
    PasswordIsEmpty = "password-empty",
    PasswordInvalid = "password-invalid",
    Camera = "camera",
    Gallery = "gallery",
    ChooseImage = "choose-image",
    ServiceCategoryLabel = "category",
    Next = "next",
    Cancel = "cancel",
    GenericError = "error-generic",
    RequiredFields = "required-fields",
    CheckTheRequiredFields = "check-the-required-fields",
    WaitingApprovation = "waiting-approvation",
    ExpiresIn = "expires-in",
    Days = "days",
    ExpiresToday = "expires-today",
    CarAdRefused = "car-ad-refused",
    CarAdExpired = "car-ad-expired",
    WelcomeSlideTitles = 'welcome-slide-titles',
    WelcomeSlidesMsgs = 'welcome-slide-msgs',
    SeeCarAds = "see-car-ads",
    NotYet = "not-yet",
    Profile = "profile",
    LoginAlertMsgProfile = "login-alert-msg-profile",

//Recover Password
    RecoverPassword = "recover-password",
    RecoverPasswordText = "recover-password-text",
    RecoverPasswordPopupTitle = "recover-password-popup-title",
    RecoverPasswordPopupMsg = "recover-password-popup-msg",
//Home - Feature/Favorite CarAds
    AdsTitle = "car-ad ",
    FeaturedAds = "featured-car-ads",
    FavoriteAds = "favorite-car-ads",
    EmptyFavoriteAds = "empty-favorite-car-ads",
    EmptyFeaturedAds = "empty-featured-car-ads",
    CarAdAddedToFavorites = "car-ad-added-to-favorite",
    CarAdRemovedFromFavorites = "car-ad-removed-from-favorites",
    YouNeedBeLoggedIn = "you-need-be-logged-in",
    GoToLogin = "go-to-login",

//Created CarAds
    EmptyCreatedCarAds = "empty-created-car-ads",
    CreateCarAd = "create-car-ad ",
    EditCarAd = "edit-car-ad ",
    CarAdsCreated = "car-ads -created",
    JapaneseLevels = "create-car-ad-japanese-leves",
    NoServicesTypesRegistered = "no-service-type-registered",
    NoInformation = "no-information",
    NoCityFound = "no-city-found",
    WhichCity = "which-city",
  
//Profile
    AccountTitle = "account-title",
    EditAccount = "edit-account",
    ChangePassword = "change-password",
    Logout = "logout",

//CreateCarAd - Step 1
    CarAdTitle = "car-ad-title",
    ServiceTypeLabel = "service-type",
    ServiceCategory = "service-category",
    CarAdDescription = "car-ad-description",
    FieldIsEmpty = "title-is-empty",

//CreateCarAd - Step 2
    StateLabel = "state",
    CityLabel = "city",
    Salary = "salary",
    Contact = "contacty",
    Bonus = "bonus",
    Genre = "genre",
    JapaneseLevel = "japanese-level",
    HasHousing = "has-housing",

//CreateCarAd - Step 3
    Schedule = "schedule",
    AddSchedule = "add-schedule",

//CreateCarAd - Step 4
    Photos = "photos",
    AddPhoto = "add-photo",

//CarAdDetails
    CarAdRepublishedInAnalysisMsg = "car-ad-in-analysis-after-updated",
    CarAdDeleted = "car-ad -deleted",
    DeleteCarAdTitle = "car-ad -delete-title",
    DeleteCarAdMsg = 'car-ad -delete-msg',
    RepublishCarAdTitle = "republish-car-ad -title",
    RepublishCarAdMsg = "republish-car-ad -msg",
    RepublishCarAdFailed = "republish-car-ad -failed",
    DeleteCarAdFailed = "delete-car-ad -failed",
    Description = "description",
    MakeACall = "make-a-call",
    HasBonus = "has-bonus",
    JapaneseLanguage = "japanese-language",
    HasHousingLabel = "has-housing-label",
    LoginAlertMsgCarAdDetails = "login-alert-msg",

//Filter
    FilterTitle = "filter-title",
    ValueLabel = "value-label",
    Apply = "apply",

//EditProfile
    EditAccountTitle = "edit-profile-title",
    Birthday = "birthday",
    Occupatioon = "occupation",
    PhoneNumber = "phone-number",
    Address = "address",
    EnterYourBirthday = "enter-your-birthday",
    EnterYourOccupation = "enter-your-occupation",
    EnterYourPhoneNumber = "enter-your-phone-number",
    EnterYourAddress = "enter-your-address",
    Save = "save",
    ProfileUpdatedSuccessful = "profile-updated-successful",

//ChangePassword
    OldPassword = "old-password",
    NewPassword = "new-password",
    SuccessChangePassword = "success-change-password",
    FailedChangePassword = "failed-change-password",

//CreateCarAd
    CarAdInAnalysis = "car-ad-in-analysis",
    CarAdInAnalysisMsg = "car-ad-in-analysis-msg",
    LoginAlertMsgCreateCarAd = "login-alert-msg-create-car-ad",
    CarAdUpdatesInAnalysis = "car-ad-updated-in-analysis-msg";

final ja = {
  AppTitle: "Hotaru Carros",
  CreateAccount: "会員登録",
  Login: "ログイン",
  WhatYourName: "お名前は？",
  AddProfilePhoto: "あなたのプロフィールに写真を追加するのはどうですか？",
  WhatYourEmail: "あなたのe-mailは？",
  CreateAPassword: "パスワード作成",
  RegisterCompletedTitle: "登録完了",
  RegisterCompeltedMsg: "登録は正常に完了しました",
  OK: "OK",
  Welcome: "ようこそ！",
  Email: "Email",
  Name: "お名前",
  EnterYourEmail: "e-mailを入力してください",
  EnterYourName: "お名前を入力してください",
  Password: "パスワード",
  EnterYourPassword: "パスワードを入力してください",
  ForgotPassword: "パスワードを忘れましたか？",
  Enter: "サインイン",
  NewUserQuestion: "新規ユーザーですか？",
  Register: "登録",
  EmailIsEmpty: "e-mailを入力してください",
  EmailInvalid: "E-mailが無効です",
  PasswordIsEmpty: "パスワードを入力してください",
  PasswordInvalid: "パスワードは６文字以上で入力してください",
  RecoverPassword: "パスワードを回復",
  RecoverPasswordText:
  "メールアドレスを入力して、パスワードをリセットする為のリンクを受け取ります",
  RecoverPasswordPopupTitle: "メールを送信しました",
  RecoverPasswordPopupMsg: "受信トレイを確認ください",
  NameIsEmpty: "お名前を入力してください",
  Camera: "カメラ",
  Gallery: "ギャラリー",
  ChooseImage: "画像を選択",
  AdsTitle: "求人",
  FeaturedAds: "注目の求人",
  FavoriteAds: "お気に入り",
  EmptyFavoriteAds: "まだお気に入りに保存がありません！",
  EmptyFeaturedAds: "残念ながら追加された求人はございません。",
  EmptyCreatedCarAds: "まだ求人を作成しておりません。",
  CreateCarAd: "求人作成",
  EditCarAd : "求人編集",
  CarAdsCreated: "作成された求人",
  AccountTitle: "アカウント",
  EditAccount: "アカウント編集",
  ChangePassword: "パスワード変更",
  Logout: "ログアウト",
  CarAdAddedToFavorites: "お気に入りに追加",
  CarAdRemovedFromFavorites: "お気に入りを削除しました。",
  CarAdTitle: "求人タイトル",
  ServiceCategoryLabel: "職種",
  ServiceTypeLabel: "職業",
  ServiceCategory: "職種",
  CarAdDescription: "仕事の内容",
  Next: "次",
  StateLabel: "都道府県",
  CityLabel: "市町村",
  Bonus: "ボーナス",
  Genre: "性別",
  JapaneseLevel: "日本語力",
  HasHousing: "住まい",
  Schedule: "勤務時間",
  AddSchedule:
  "勤務時間やシフトを説明してください。",
  Photos: "写真",
  AddPhoto: "写真を追加",
  CarAdInAnalysis: "求人を確認中です。",
  CarAdInAnalysisMsg:
  "求人が作成されました。確認中です。",
  CarAdRepublishedInAnalysisMsg : "求人が投稿される前に確認致します。",
  FieldIsEmpty: "必須",
  CarAdDeleted : "求人が削除されました。",
  DeleteCarAdTitle : "求人を削除",
  DeleteCarAdMsg : "求人を削除しますか？",
  RepublishCarAdTitle : "求人を再投稿しますか？",
  RepublishCarAdMsg : "この求人を再投稿しますか？",
  RepublishCarAdFailed : "求人を再投稿出来ません。",
  DeleteCarAdFailed : "求人を削除出来ませんでした。",
  Cancel : "キャンセル",
  YES : "はい",
  FilterTitle : "条件絞り込み",
  ValueLabel : "値段",
  Apply : "条件決定",
  EditAccountTitle : "アカウント編集",
  Birthday : "生年月日",
  Occupatioon : "職業",
  PhoneNumber : "電話番号",
  Address : "住所",
  EnterYourBirthday : "いつ生まれましたか？",
  EnterYourOccupation : "現在の職業は何ですか？",
  EnterYourPhoneNumber : "電話番号を入力してください。",
  EnterYourAddress : "住所",
  Save : "保存",
  Contact : "連絡先",
  OldPassword : "旧パスワード",
  NewPassword : "新パスワード",
  SuccessChangePassword : "パスワードが変更されました。",
  FailedChangePassword : "パスワード変更エラー、旧パスワードが正しく入力されましたか？.",
  JapaneseLevels : ["初級","中級","上級","ネイティブ"],
  GenericError : "エラー",
  NoServicesTypesRegistered : "現在登録されている求人にはございません。",
  NoInformation : "情報が見つかりませんでした。",
  NoCityFound : "市町村が見つかりませんでした。",
  WhichCity : "どちらの市町村ですか？",
  CarAdUpdatesInAnalysis : "あなたの求人は更新されており、公開前に確認致します。",
  RequiredFields : "必須",
  CheckTheRequiredFields : "上記の項目を確認して下さい。",
  ProfileUpdatedSuccessful :  "情報が更新されました。",
  Description : "説明",
  MakeACall : "お問い合わせ",
  HasBonus : "ボーナス有り",
  JapaneseLanguage : "日本語力",
  HasHousingLabel : "住まい有り",
  WaitingApprovation : "承認待ち",
  ExpiresIn : "有効期限",
  Days : "日",
  ExpiresToday : "本日有効切れ",
  CarAdRefused : "求人が承認されませんでした。",
  CarAdExpired : "求人有効切れ",
  WelcomeSlideTitles : [
    "ホタルとは？",
    "自分にピッタリな求人を探そう",
    "掲載をお考えの企業様へ"
  ],

  WelcomeSlidesMsgs :  [
    "ホタルは無料求人情報アプリで、お仕事を探すこともでき掲載もできます。",
    "ご希望の条件で求人情報をお探しできます。",
        "全面的にサポート致します。"
  ],
  Salary: "時給",
  SeeCarAds : "求人を見る",
  YouNeedBeLoggedIn : "ログインをしてお気に入りの確認や追加が出来ます",
  GoToLogin : "ログイン",
  NotYet : "いいえ",
  LoginAlertMsgCarAdDetails : "広告主に連絡するにはログインしてください。",
  LoginAlertMsgCreateCarAd : "求人を掲載するにはログインが必要です。今すぐログインしますか？",
  Profile : "プロフィール",
  LoginAlertMsgProfile : "現在ログインしていません。今すぐログインしますか？"

};

final pt = {
  AppTitle: "Hotaru Carros",
  CreateAccount: "Criar conta",
  Login: "Login",
  WhatYourName: "Qual é o seu nome?",
  AddProfilePhoto: "Que tal adicionar uma foto para o seu perfil?",
  WhatYourEmail: "Qual o seu e-mail?",
  CreateAPassword: "Crie uma senha",
  RegisterCompletedTitle: "Cadastro concluído",
  RegisterCompeltedMsg: "Seu cadastro foi concluído com sucesso",
  OK: "OK",
  Welcome: "Bem-vindo!",
  Email: "Email",
  Name: "Nome",
  EnterYourEmail: "Digite seu e-mail",
  EnterYourName: "Digite seu nome",
  Password: "Senha",
  EnterYourPassword: "Digite sua senha",
  ForgotPassword: "Esqueceu a senha?",
  Enter: "Entrar",
  NewUserQuestion: "Novo usuário?",
  Register: "Cadastre-se",
  EmailIsEmpty: "Por favor digite seu e-mail",
  EmailInvalid: "E-mail inválido",
  PasswordIsEmpty: "Por favor digite sua senha",
  PasswordInvalid: "A senha precisa ter no mínimo 6 caracteres",
  RecoverPassword: "Recuperar senha",
  RecoverPasswordText:
      "Insira seu e-mail e receba um link para redefinir a sua senha.",
  RecoverPasswordPopupTitle: "E-mail enviado",
  RecoverPasswordPopupMsg: "Cheque sua caixa de entrada",
  NameIsEmpty: "Por favor digite seu nome",
  Camera: "Câmera",
  Gallery: "Galeria",
  ChooseImage: "Escolher imagem",
  FeaturedAds: "Em destaque",
  FavoriteAds: "Favoritos",
  AccountTitle: "Conta",
  EditAccount: "Editar conta",
  ChangePassword: "Alterar senha",
  Logout: "Sair",
  ServiceCategoryLabel: "Categoria do serviço",
  ServiceTypeLabel: "Tipo de serviço",
  ServiceCategory: "Categoria do serviço",
  Next: "Próximo",
  StateLabel: "Estado",
  CityLabel: "Cidade",
  Bonus: "Bônus",
  Genre: "Gênero",
  JapaneseLevel: "Japonês",
  HasHousing: "Moradia",
  Schedule: "Horários",
  ValueLabel : "Valor por hora",
  AddSchedule:
      "Informe os horários ou descreva-os informando o turno e/ou escala de trabalho.",
  Photos: "Fotos",
  AddPhoto: "Adicionar foto",
  FieldIsEmpty: "Campo obrigatório",
  Cancel : "Cancelar",
  YES : "Sim",
  FilterTitle : "Filtro",
  Apply : "Aplicar",
  EditAccountTitle : "Editar conta",
  Birthday : "Data de nascimento",
  Occupatioon : "Ocupação",
  PhoneNumber : "Número de telefone",
  Address : "Endereço",
  EnterYourBirthday : "Quando você nasceu?",
  EnterYourOccupation : "Qual sua ocupação atualmente?",
  EnterYourPhoneNumber : "Informe seu número de telefone",
  EnterYourAddress : "Qual seu endereço?",
  Save : "Salvar",
  Contact : "Número de contato",
  OldPassword : "Senha antiga",
  NewPassword : "Nova senha",
  SuccessChangePassword : "Senha alterada com sucesso.",
  FailedChangePassword : "Erro ao alterar senha, verifique se digitou corretamente a senha antiga.",
  JapaneseLevels : ["Básico","Intermediário","Business","Avançado","Fluente"],
  GenericError : "Erro inesperado",
  NoServicesTypesRegistered : "Não existem tipos de serviço cadastrados no momento.",
  NoInformation : "Nenhuma informação encontrada",
  NoCityFound : "Nenhuma cidade encontrada",
  WhichCity : "Em qual cidade?",
  RequiredFields : "Campos obrigatórios",
  CheckTheRequiredFields : "Por favor verifique os campos acima!",
  ProfileUpdatedSuccessful :  "Dados atualizados com sucesso.",
  Description : "Descrição",
  MakeACall : "Entrar em contato",
  HasBonus : "Possui bônus",
  JapaneseLanguage : "Língua japonesa",
  HasHousingLabel : "Possui moradia",
  WaitingApprovation : "Aguardando aprovação",
  ExpiresIn : "Expira em",
  Days : "dias",
  ExpiresToday : "Expira hoje",

  Salary: "Valor por hora",
  GoToLogin : "Ir para login",
  NotYet : "Agora não",
  LoginAlertMsgCarAdDetails : "Realize login para entrar em contato com o anunciante.",
  Profile : "Perfil",
  LoginAlertMsgProfile : "Nenhum usuário logado no momento. Deseja fazer login agora?",

  //To Translate
  CarAdDescription: "Descrição do anúncio",
  CarAdTitle: "Título do anúncio",
  LoginAlertMsgCreateCarAd : "Você precisa estar logado para criar novos anúncios. Deseja fazer login agora?",
  YouNeedBeLoggedIn : "Você precisa realizar login para ver ou adicionar anúncios aos favoritos",
  CarAdRefused : "Anúncio recusado",
  CarAdExpired : "Anúncio expirado",
  CarAdUpdatesInAnalysis : "Sue anúncio foi atualizado e passará por uma análise antes de ser publicado.",
  CarAdDeleted : "Anúncio removido com sucesso.",
  DeleteCarAdTitle : "Deletar anúncio",
  DeleteCarAdMsg : "Deseja realmente deletar esse anúncio?",
  RepublishCarAdTitle : "Republicar anúncio",
  RepublishCarAdMsg : "Deseja republicar esse anúncio?",
  RepublishCarAdFailed : "Falha ao republicar o anúncio",
  DeleteCarAdFailed : "Falha ao remover o anúncio",
  CarAdInAnalysis: "Anúncio em análise",
  CarAdInAnalysisMsg:
  "Seu Anúncio foi criado e passará por uma análise antes de ser publicado.",
  CarAdRepublishedInAnalysisMsg : "Seu anúncio passará por uma análise antes de ser republicado.",
  EmptyFeaturedAds: "Ah, que pena! Ainda não há nenhum anúncio em destaque.",
  EmptyCreatedCarAds: "Você ainda não criou nenhum anúncio!",
  CreateCarAd: "Criar anúncio",
  EditCarAd : "Editar anúncio",
  CarAdsCreated: "Anúncios criados",
  CarAdRemovedFromFavorites: "Anúncio removido dos favoritos",
  CarAdAddedToFavorites: "Anúncio adicionado aos favoritos",
  EmptyFavoriteAds: "Você ainda não possui nenhum anúncio salvo nos favoritos!",
  AdsTitle: "Anúncios",
  SeeCarAds : "Ver anúncios",
  WelcomeSlideTitles : ["Aplicativo Hotaru","Encontre anúncios","Divulgue anúncios"],
  WelcomeSlidesMsgs :  [
  "O app que veio para mudar a maneira de encontrar e divulgar veículos no Japão.",
  "Os melhores anúncios de carro do Japão estão aqui, todas as informações necessárias para você.",
  "Para você que tem uma anúncio para divulgar, aqui é o melhor lugar, seja bem-vindo ao Hotaru!",],
};

final en = {
  AppTitle: "Hotaru",
  CreateAccount: "Create account",
  Login: "Login",
  WhatYourName: "What is your name?",
  AddProfilePhoto: "How about adding a photo to your profile?",
  WhatYourEmail: "What is your e-mail?",
  CreateAPassword: "Create a password",
  RegisterCompletedTitle: "Registration completed",
  RegisterCompeltedMsg: "Your registration has completed successfully",
  OK: "OK",
  Welcome: "Welcome!",
  Email: "Email",
  Name: "Name",
  EnterYourEmail: "Type your email",
  EnterYourName: "Type your name",
  Password: "Password",
  EnterYourPassword: "Type your password",
  ForgotPassword: "Forgot your password?",
  Enter: "Enter",
  NewUserQuestion: "New user?",
  Register: "Register",
  EmailIsEmpty: "Please type your email",
  EmailInvalid: "Email invalid",
  PasswordIsEmpty: "Please type your password",
  PasswordInvalid: "Password must be at least 6 characters",
  RecoverPassword: "Recover password",
  RecoverPasswordText:
  "Enter your email and receive a link to reset your password.",
  RecoverPasswordPopupTitle: "Email invalid",
  RecoverPasswordPopupMsg: "Check your inbox",
  NameIsEmpty: "Please type your name",
  Camera: "Camera",
  Gallery: "Gallery",
  ChooseImage: "Choose image",
  AdsTitle: "CarAds",
  FeaturedAds: "Highlighted",
  FavoriteAds: "Favorites",
  EmptyFavoriteAds: "You do not have any saved car-ad vacancies yet!",
  EmptyFeaturedAds: "Oh, what a pity! There are no highlighted car-ad vacancies yet.",
  EmptyCreatedCarAds: "You have not created any car-ad vacancie yet!",
  CreateCarAd: "Create a car-ad vacancy",
  EditCarAd : "Edit car-ad vacancy",
  CarAdsCreated: "CarAds vacancies created",
  AccountTitle: "Account",
  EditAccount: "Edit account",
  ChangePassword: "Change password",
  Logout: "Logout",
  CarAdAddedToFavorites: "CarAd vacancy added to favorites",
  CarAdRemovedFromFavorites: "CarAd vacancy removed from favorites",
  CarAdTitle: "CarAd vacancy title",
  ServiceCategoryLabel: "Service category",
  ServiceTypeLabel: "Service type",
  ServiceCategory: "Service category",
  CarAdDescription: "CarAd vacancy description",
  Next: "Next",
  StateLabel: "State",
  CityLabel: "City",
  Salary: "Valur per hour",
  Bonus: "Bonus",
  Genre: "Genre",
  JapaneseLevel: "Japanese",
  HasHousing: "Huosing available",
  Schedule: "Schedules",
  AddSchedule:
  "Enter the schedules or describe them informing the shift and/or work schedule.",
  Photos: "Photos",
  AddPhoto: "Add photo",
  CarAdInAnalysis: "CarAd vacancy in analysis",
  CarAdInAnalysisMsg:
  "Your car-ad vacancy has been created and will be reviewed before it is published.",
  CarAdRepublishedInAnalysisMsg : "Your car-ad vacancy will be reviewed before being republished.",
  FieldIsEmpty: "Field required",
  CarAdDeleted : "CarAd vacancy removed successfully",
  DeleteCarAdTitle : "Delete car-ad vacancy",
  DeleteCarAdMsg : "Do you really want to delete this car-ad vacancy?",
  RepublishCarAdTitle : "Republish car-ad vacancy",
  RepublishCarAdMsg : "Do you want republish this car-ad vacancy?",
  RepublishCarAdFailed : "Failed to republish the car-ad vacancy",
  DeleteCarAdFailed : "Failed to remove the car-ad vacancy",
  Cancel : "Cancel",
  YES : "Yes",
  FilterTitle : "Filter",
  ValueLabel : "Value",
  Apply : "Apply",
  EditAccountTitle : "Edit account",
  Birthday : "Birthday",
  Occupatioon : "Occupation",
  PhoneNumber : "Phone number",
  Address : "Address",
  EnterYourBirthday : "When you were born?",
  EnterYourOccupation : "What is your current occupation",
  EnterYourPhoneNumber : "Enter your phone number",
  EnterYourAddress : "What is your address?",
  Save : "Save",
  Contact : "Contact phone number",
  OldPassword : "Old password",
  NewPassword : "New password",
  SuccessChangePassword : "Password changed successfully.",
  FailedChangePassword : "Error while changing password, make sure you have entered the old password correctly.",
  JapaneseLevels : ["Basic","Intermediary","Business","Advanced","Fluent"],
  GenericError : "Unexpected error",
  NoServicesTypesRegistered : "There are no service types currently registered.",
  NoInformation : "No information found",
  NoCityFound : "No city found",
  WhichCity : "Which city?",
  CarAdUpdatesInAnalysis : "Your car-ad has been updated and will be reviewed before it is published.",
  RequiredFields : "Required fields",
  CheckTheRequiredFields : "Please check the fields above",
  ProfileUpdatedSuccessful :  "Data updated sucsessfully",
  Description : "Description",
  MakeACall : "Make a call",
  HasBonus : "Has bonus",
  JapaneseLanguage : "Japanese language",
  HasHousingLabel : "Has housing",
  WaitingApprovation : "Waiting for approval",
  ExpiresIn : "Expires in",
  Days : "days",
  ExpiresToday : "Expires today",
  CarAdRefused : "CarAd advertisement refused",
  CarAdExpired : "CarAd advertisement expired",
  WelcomeSlideTitles : ["App Hotaru","Find car-ads","Advertise car-ads"],
  WelcomeSlidesMsgs :  [
    "The app that came to change the way to find and advertise car-ad in Japan.",
    "The best car-ads in Japan are here, all the information you need.",
    "For you who have a car-ad to advertise, here is the best place, welcome to Hotaru!",]

};
